### ISSUE TITLE
Issue with Footer.vue after latest dependency update

### ISSUE THREAD

**Issue by TreeIsLife2** [MediaWikiAGE/MAGE#75] opened 2021-10-30 18:51 UTC
Error looks like:

```
ERROR in
(path to MAGE's location)\MAGE\src\components\Footer.vue
  1:1  error  Component name "Footer" should always be multi-word  vue/multi-word-component-names
```

**Comment by AttemptToCallNil** [comment] 2021-10-30 19:07
Yes, that's one of the changed lints. Strangely enough, this specific component was not giving me errors when I was testing the update. I also can't reproduce the issue by running `pnpm run electron:serve` (which made the errors with other components appear), but I do believe this issue is valid.

**Comment by AttemptToCallNil** [comment] 2021-10-30 19:11
Does #76 resolve this issue?

**Comment by TreeIsLife2** [comment] 2021-10-30 19:18
Yes, it does.

**Comment by AttemptToCallNil** [comment] 2021-10-31 12:40
As #76 is now merged, I'm closing this issue.

**Closed by AttemptToCallNil** 2021-10-31 12:40 UTC
